services:
  - type: web
    name: zapchat
    runtime: node
    plan: free
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
        generateValue: false
      - key: CLIENT_URL
        value: "*"
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: MONGODB_URI
        sync: false
    buildFilters:
      - "!**/.env"
      - "!**/.env.*"
      - "!**/node_modules"
